### PR TITLE
Orthanc 1.5.7

### PR DESCRIPTION
**Pull request by Betalos**
- add debian 9 build instractions (static build)
- enhance LookupResources method

### CODE REVIEW

**Comment by ihor-mozil** [comment]
Would it be possible to rebase this pull request to the latest changes in the Orthanc 1.5.7 branch?

**Comment by Betalos** [comment]
@ihor-mozil, yes you could.

**Comment by ihor-mozil** [comment]
I'm asking for a rebase, because I've already merged the pull request #19, which contains lot of changes. I can not merge the pull request #20 because this branch has conflicts that must be resolved.

**Comment by Betalos** [comment]
I see i'll try to fix the conflicts with the main branch

**Comment by Betalos** [comment]
@ihor-mozil I've fixed the conflicts now you can merge safly.

**Comment by ihor-mozil** [comment]
@Betalos Looks good. Thank you!

**Pull request merged**
