### PR TITLE
initial working plugin support Orthanc 1.5.7

### PR DESCRIPTION
**Pull request by Betalos**

### CODE REVIEW

**Comment by kosch** [comment]
Thanks @Betalos.

@ihor-mozil Can you have a look at the changes and maybe you can integrate them. Thanks :-)

**Comment by Betalos** [comment]
@kosch your wellcome budy. 
Well I did some refactoring to the code by changing stream document building to make_document and kvp.

**Comment by ihor-mozil** [comment]
Looks good to me, I didn't test new methods though.
@Betalos great work. It's still tough for me to find time for this, I hope I'll be able to add unit tests for the new methods.

**Comment by Betalos** [comment]
hi @ihor-mozil, yeah I know it get tough to find time, well I just did some reverse ingeniring stuff (the lookupResources need some enhancements cuz it take time with a large database (100gb) up to 7s.
so i'll keep working on it.
I also notised a warning in Orthanc saying : "Your database index plugin is not compatible with multiple Orthanc writers".

**Pull request merged**
