### PR TITLE
Eliminate boost dependency

### PR DESCRIPTION
**Pull request by espakm**
This raises the minimum requirement to C++17.

### CODE REVIEW

**Comment by kosch** [comment]
Well, I would only add special cases for boost usage, if somebody really needs it. But I'm not a C++ developer, so its your decision :-)

**Comment by espakm** [comment]
I updated the PR so that it can be merged cleanly. (It conflicted with the jsoncpp fix that is now on master.)

Boost is a collection of libraries that extend the functionality of the C++ standard library. It is written in the style and along guidelines that match with those of the C++ standard. The aim is that one day these libraries can be integrated in the standard. According to this, Boost is always a bit ahead, but the standard is "catching up".

In the mongodb plugin boost was used only for things that are now all part of the standard. However, one class, the `scoped_lock` appeared only in C++17. The C++17 support has not arrived to all platforms yet. So, the question really is if there is a platform on which this code can't be compiled, and anyone still needs that.

This I can't tell.

I had a similar problem with the filesystem library. Although, I had C++17 compiler on windows, mac and linux, the C++ library on mac did not contain the filesystem library, or it was in a different header or so.

**Comment by espakm** [comment]
Found that C++11 provides `std::lock_guard` for the same purpose, so `std::scoped_lock` to that, and reverted the minimum requirement to C++14 as it was.

`std::scoped_lock` supersedes `std::lock_guard`, as it can lock multiple mutexes at the same time, but here only one mutex was locked, so lock_guard should be fine. And we do not need to give up old platforms.

I believe it is safe to merge the PR now.

**Review by ihor-mozil — APPROVED** [review]
Good work, less dependencies is better.

**Comment by ihor-mozil** [comment]
The bsoncxx still use boost, so it's still required to build the plugin.

**Comment by espakm** [comment]
Thanks for merging!
In my build BSONCXX_POLY_USE_BOOST is OFF (as default, didn't touch it), and as far as I see, boost was not used at all. The C++ sources use ifdef-s everywhere and can compile without boost. However, I found some checks in CMake and it looks that Boost is required with MSVC. Maybe you tried it on Windows?

**Comment by ihor-mozil** [comment]
There was a tricky part with windows and no boost as well as bugs in the Visual Studio, it's good MS fixed it in the latest versions. Finally I was able to build the mongo-cxx-driver with the following cmake (no boost):

cmake -G "Visual Studio 15 Win64" -DCMAKE_INSTALL_PREFIX="C:\mongo-cxx-driver" -DBSONCXX_POLY_USE_STD=ON -DCMAKE_PREFIX_PATH="C:\mongo-c-driver" -DCMAKE_CXX_FLAGS="/std:c++17  /Zc:__cplusplus /D_ENABLE_EXTENDED_ALIGNED_STORAGE /EHsc" ..

After that there were some issues with the mongo driver the std::string_view has no to_string() method, but it is in boost. Fixed, the pool request is coming.

**Pull request merged**
