### PR TITLE
Enhance performance by changing db structure.

### PR DESCRIPTION
**Pull request by Betalos**
Hello @kosch @ihor-mozil @andrewDubyk, I am sorry I didn't checked the main repos.
So now I've synced with the main and pushed into the master.
In this pull I have changed the db structure to allow for more performance in the Q/R (LookupResources).
If this an update it requires to run a script I added to Scripts folder It's a python3.5> one and it's requirements also, this is how to use it:
```python
python3.5 Scripts/db_update.py DB_Connection_Uri
``` 
With this change I have successfully managed to shape 50% to 75% performance with the query.
This update is fully working with 1.7.3 latest ORTHANC version and mongodb 4.4 unless there is an issue I am not aware of.

### CODE REVIEW

**Comment by kosch** [comment]
Well, it has to be tested with MongoDB 3.6 too. Furthermore: Its possible to get around the db_update.py? e.g. by introducing compatibility layer or on demand migration of entries when they are read/written?

**Comment by Betalos** [comment]
Hi @kosch, Well I am not sure if plugin would work with 3.6 cuz I think in the aggregation I am using some new operators (not fully sure).
About the db_update I am not that powerfull in C++ (I am good in mongodb) so I wanted to make it with the plugin but I did not find a way to do it.

**Comment by Betalos** [comment]
One more thing the python script could rewriting as .js file and be executed by mongo binary since it's just a basic mongo queries, the only python related is the multiprocessing for speeding the migration for large datasets.

**Comment by ooskapenaar** [comment]
@Betalos I had a look at this code.  I think it achieves the same effect as a PR https://github.com/Doc-Cirrus/orthanc-mongodb/pull/29  which does not need any scripting or DB structural change and also achieves a roughly 10x speed increase.  Can you pls take a look and comment?

Is it possible to come back to a single code base?

If we change the DB Structure for the Plugin, we would do that as @kosch suggested in a backward compatible way, or in a way that migrates the entire DB from within the plugin at Init time.

**Comment by Betalos** [comment]
@ooskapenaar I see the changes, I think it would help also to add index for the value.
But the changes I've made are in the db structure that are used when doing DbLookup (search/query), those changes helped cut down the time by a lot.
I agree the the db changes should be a backward compatible.
The script I made (python) could be rewriten in js (executed natively with mongo cmd)  since it's just basic mongo commands.
the script could be executed in the plugin initialization and the db version would be upgraded (not executed each time).

**Comment by ooskapenaar** [comment]
We have now spent a lot of time optimising the queries and believe that we can move forward with the current structure and still be faster than the PostgresSQL plugin.  Since we cannot change the DB Schema, I am closing this PR.

The recommended way to optimise the functioning of the plugIn is to Limit the numbers of results in the configuration:
``"LimitFindResults" : 100,``
``"LimitFindInstances" : 100,``
 
Thanks very much for your work on the plugin @Betalos , I hope you can continue to benefit from the plugin.

**Comment by Betalos** [comment]
@ooskapenaar, You're welcome.
Sorry to hear that you cannot accept my pull request. I know it could be a problem changing the DB structure in prod env. But in my defense I didn't find another way.
In the future I see if it's still possible to cherry pick pull request (upcoming 1.9.3 support and with transactions for mongo@4.0 +)

**Pull request closed without merging**
